# Generated by Django 2.2.8 on 2020-02-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200202_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecvalues',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='product.Product'),
        ),
    ]
