# Generated by Django 2.2.8 on 2020-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200229_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
