# Generated by Django 2.2.8 on 2020-03-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('category_spec_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='product.Specification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductSpecifications',
        ),
        migrations.AddField(
            model_name='product',
            name='parametrs',
            field=models.ManyToManyField(to='product.ValueSpecification'),
        ),
    ]
