# Generated by Django 2.2.8 on 2020-03-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200324_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parametrs',
            new_name='specification',
        ),
    ]
