# Generated by Django 2.2.8 on 2020-05-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200507_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
