# Generated by Django 2.2.8 on 2020-03-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='order',
        ),
    ]
