# Generated by Django 2.2.8 on 2020-03-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
    ]
