# Generated by Django 2.2.8 on 2020-03-01 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_address_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
