# Generated by Django 2.2.8 on 2020-03-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200301_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
